name: Build and Push to Quay.io

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Podman
      run: |
        sudo apt update
        sudo apt install -y podman

    - name: Login to Quay.io
      run: |
        podman login -u ${{ secrets.QUAY_USERNAME }} -p ${{ secrets.QUAY_PASSWORD }} quay.io

    - name: Build and Push Image
      run: |
        podman build -t quay.io/${{ secrets.QUAY_USERNAME }}/rubymaintain:latest .
        podman push quay.io/${{ secrets.QUAY_USERNAME }}/rubymaintain:latest
